# local or remote production deployment
# Usage:
#     1. Edit prod.env (if necessary)
#
#     2. docker compose --env-file prod.env up --build -d

services:
  nginx:
    build:
      context: .
      target: nginx
    environment:
      SCRIPT_NAME: '' # can be null (i.e., ''), but not unset for envsubst
    ports:
      - "${PORT:-80}:8080"
    depends_on:
      - django
    restart: always
    volumes:
      - gunicorn-socket:/run/gunicorn

  django:
    build:
      context: .
      target: prod
    depends_on:
      db:
        condition: service_healthy
    restart: always
    environment:
      ALLOWED_HOSTS:
      BRAPI_URL: https://arsiaamp3ggrpts.agron.iastate.edu/gringlobal/brapi/v2
      DEBUG:
      PGHOST: /run/postgresql
      PGPORT:
      PGPASSWORD:
      PGUSER:
      PGDATABASE: postgres
      SCRIPT_NAME: ''
    volumes:
      - gunicorn-socket:/run/gunicorn
      - postgres-socket:/run/postgresql
      - /app/data

  db:
    build:
      context: .
      target: db
    healthcheck:
      test: "gosu postgres pg_isready || exit 1"
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: unused
      POSTGRES_INITDB_ARGS: --auth=peer
    volumes:
      - postgres-socket:/run/postgresql
      - /var/lib/postgresql/data
# don't listen on TCP port; write optimizations
    command: ["-c", "listen_addresses=",
              "-c", "wal_level=minimal",
              "-c", "max_wal_senders=0",
              "-c", "synchronous_commit=off"]

volumes:
  gunicorn-socket:
  postgres-socket:
