on: [workflow_dispatch]

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache/restore@v4
        id: grin-cache-restore
        with:
          path: ./data
          key: grin-brapi-data
      - name: Download JSON
        env:
          BRAPI_URL: https://arsiaamp3ggrpts.agron.iastate.edu/gringlobal/brapi/v2
        run: PATH=$PWD/scripts:$PATH bash ./scripts/load-all.sh -d
      - uses: actions/cache/save@v4
        if: always()
        id: save-grin-cache
        with:
          path: ./data
          key: grin-brapi-data
      - uses: oras-project/setup-oras@v1
      - name: Publish
        shell: bash
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | oras login -u ${{ github.actor }} --password-stdin ghcr.io
          oras push ghcr.io/${GITHUB_REPOSITORY,,}:data-latest ./data
